import { useMemo, useState } from "react";
import { DemoAgentBuilderAdapter, EMPTY_DRAFT, type AgentBuilderAdapter, type BuilderDraftView, type BuilderTab, type DirectoryAgent, type PreflightRow } from "../../features/agent-builder";
import { ConversationalBuilder } from "./ConversationalBuilder";
import { AgentDirectory } from "./AgentDirectory";
import { PreflightPanel } from "./PreflightPanel";
import { StructuredBuilder } from "./StructuredBuilder";
import "./agent-builder.css";
interface AgentBuilderWorkspaceProps { readonly adapter?: AgentBuilderAdapter; readonly initialDraft?: BuilderDraftView; readonly initialDirectory?: readonly DirectoryAgent[]; }
export function AgentBuilderWorkspace({ adapter: supplied, initialDraft = EMPTY_DRAFT, initialDirectory = [] }: AgentBuilderWorkspaceProps) {
  const adapter = useMemo(() => supplied ?? new DemoAgentBuilderAdapter(), [supplied]); const [draft, setDraft] = useState(initialDraft); const [tab, setTab] = useState<BuilderTab>("instructions"); const [rows, setRows] = useState<readonly PreflightRow[]>([]); const [busy, setBusy] = useState<"proposal" | "preflight" | "test" | "publish" | null>(null); const [testInput, setTestInput] = useState(""); const [testOutput, setTestOutput] = useState(""); const [notice, setNotice] = useState(""); const [audience, setAudience] = useState("Organization directory"); const [query, setQuery] = useState(""); const [agents, setAgents] = useState<readonly DirectoryAgent[]>(initialDirectory);
  async function action<T>(kind: NonNullable<typeof busy>, work: () => Promise<T>, done: (result: T) => void) { setBusy(kind); setNotice(""); try { done(await work()); } catch (error) { setNotice(error instanceof Error ? error.message : "The action failed."); } finally { setBusy(null); } }
  const applyProposal = (prompt: string) => action("proposal", () => adapter.propose(prompt, draft), (next) => { setDraft(next); setNotice("Proposal applied. Review the effective configuration before testing."); });
  const preflight = () => action("preflight", () => adapter.preflight(draft), (next) => { setRows(next); setNotice(next.some((row) => row.status === "failed") ? "Preflight found blocking issues." : "Preflight passed for this draft revision."); });
  const runTest = () => action("test", () => adapter.test(draft, testInput), (output) => { setTestOutput(output); setNotice("Test run completed."); });
  const publish = () => action("publish", () => adapter.publish(draft, audience), (result) => setNotice(`Published version ${result.version}. Runs now resolve its immutable content hash.`));
  const favorite = (id: string, value: boolean) => action("proposal", async () => { await adapter.favorite(id, value); return value; }, () => setAgents((current) => current.map((agent) => agent.id === id ? { ...agent, favorite: value } : agent)));
  const shownAgents = agents.filter((agent) => `${agent.name} ${agent.description} ${agent.category}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="ab-page"><header className="ab-header"><div><span className="ab-eyebrow">Agent builder / Draft r{draft.revision}</span><h1>Build the operating rules,<br/>then publish the version.</h1><p>Describe the job conversationally or edit every control directly. Both views produce one inspectable effective configuration.</p></div><div className="ab-header-actions"><label>Audience<select value={audience} onChange={(event) => setAudience(event.target.value)}><option>Private</option><option>Team</option><option>Selected groups</option><option>Organization directory</option><option>Organization link</option></select></label><button className="ab-button ab-button--dark" type="button" onClick={publish} disabled={busy !== null || !rows.length || rows.some((row) => row.status !== "passed")}>{busy === "publish" ? "Publishing…" : "Publish"}<span aria-hidden="true">→</span></button></div></header>{notice && <div className="ab-notice" role="status">{notice}</div>}<div className="ab-builder-grid"><div className="ab-primary"><ConversationalBuilder onSubmit={applyProposal} disabled={busy !== null}/><StructuredBuilder draft={draft} tab={tab} onTab={setTab} onChange={(next) => { setDraft(next); setRows([]); }}/><section className="ab-test-console" aria-labelledby="test-console-title"><div><span className="ab-eyebrow">Permission-scoped preview</span><h2 id="test-console-title">Test console</h2></div><label>Sample input<textarea rows={3} value={testInput} onChange={(event) => setTestInput(event.target.value)} placeholder="Draft this week's operating review from approved project context."/></label><button className="ab-button ab-button--light" type="button" onClick={runTest} disabled={busy !== null || !testInput.trim()}>Run test<span aria-hidden="true">↗</span></button>{testOutput && <output>{testOutput}</output>}</section></div><PreflightPanel rows={rows} running={busy === "preflight"} onRun={preflight}/></div><AgentDirectory agents={shownAgents} query={query} onQuery={setQuery} onFavorite={favorite}/></main>;
}
