import { BUILDER_TABS, type BuilderDraftView, type BuilderTab } from "../../features/agent-builder/model";
interface StructuredBuilderProps { readonly draft: BuilderDraftView; readonly tab: BuilderTab; readonly onTab: (tab: BuilderTab) => void; readonly onChange: (draft: BuilderDraftView) => void; }
function ChipList({ label, values }: { readonly label: string; readonly values: readonly string[] }) { return <div className="ab-field"><span className="ab-label">{label}</span><div className="ab-chips">{values.length ? values.map((value) => <span className="ab-chip" key={value}>{value}<button type="button" aria-label={`Remove ${value}`}>×</button></span>) : <span className="ab-muted">None selected</span>}</div></div>; }
export function StructuredBuilder({ draft, tab, onTab, onChange }: StructuredBuilderProps) {
  const set = (patch: Partial<BuilderDraftView>) => onChange({ ...draft, ...patch, revision: draft.revision + 1 });
  return <section className="ab-structured" aria-label="Structured agent configuration"><div className="ab-tabs" role="tablist" aria-label="Agent configuration sections">{BUILDER_TABS.map((item) => <button key={item.id} role="tab" aria-selected={tab === item.id} className={tab === item.id ? "is-active" : ""} onClick={() => onTab(item.id)}>{item.label}</button>)}</div><div className="ab-tab-panel" role="tabpanel">
    {tab === "instructions" && <div className="ab-fields"><label>Name<input value={draft.name} onChange={(event) => set({ name: event.target.value })} placeholder="Agent name" /></label><label>Description<input value={draft.description} onChange={(event) => set({ description: event.target.value })} placeholder="One-line purpose" /></label><label>System instructions<textarea rows={10} value={draft.instructions} onChange={(event) => set({ instructions: event.target.value })} placeholder="State responsibilities, evidence requirements, and boundaries." /></label></div>}
    {tab === "model" && <div className="ab-fields"><label>Model policy<select value={draft.model} onChange={(event) => set({ model: event.target.value })}><option>Standard model policy</option><option>Research model policy</option><option>Finance model policy</option></select></label><p className="ab-note">Publishing pins the resolved provider configuration and fallback chain.</p></div>}
    {tab === "capabilities" && <div className="ab-fields"><ChipList label="Skills" values={draft.skills}/><ChipList label="Connected apps" values={draft.apps}/><ChipList label="MCP tools" values={draft.mcp}/></div>}
    {tab === "context" && <div className="ab-fields"><ChipList label="Knowledge scopes" values={draft.knowledge}/><ChipList label="Memory scopes" values={draft.memory}/><p className="ab-note">Personal memory is never attached implicitly to shared agents.</p></div>}
    {tab === "runtime" && <div className="ab-fields"><ChipList label="Capability packs" values={draft.runtime}/><p className="ab-note">Image, dependency, filesystem, network, and resource limits are resolved before publication.</p></div>}
    {tab === "permissions" && <div className="ab-fields"><ChipList label="Effective tool policy" values={draft.permissions}/><p className="ab-note">External, destructive, regulated, and administrative actions cannot silently bypass approval policy.</p></div>}
    {tab === "budget" && <div className="ab-fields"><label>Run budget<input value={draft.budget} onChange={(event) => set({ budget: event.target.value })}/></label><p className="ab-note">Token, retry, concurrency, wall-time, and cost ceilings are all enforced server-side.</p></div>}
    {tab === "evals" && <div className="ab-fields"><ChipList label="Promotion suites" values={draft.evals}/><p className="ab-note">Smoke prompts and promotion thresholds must pass against permitted test context.</p></div>}
  </div></section>;
}
