import type { BuilderDraftView, DirectoryAgent, PreflightRow } from "./model";
export interface AgentBuilderAdapter { propose(prompt: string, draft: BuilderDraftView): Promise<BuilderDraftView>; preflight(draft: BuilderDraftView): Promise<readonly PreflightRow[]>; test(draft: BuilderDraftView, input: string): Promise<string>; publish(draft: BuilderDraftView, audience: string): Promise<{ version: string; contentHash: string }>; search(query: string): Promise<readonly DirectoryAgent[]>; favorite(agentId: string, value: boolean): Promise<void>; }
export class DemoAgentBuilderAdapter implements AgentBuilderAdapter {
  async propose(prompt: string, draft: BuilderDraftView): Promise<BuilderDraftView> { const intent = prompt.trim(); if (!intent) throw new Error("Describe the agent you want to build."); return { ...draft, name: draft.name || "New department agent", description: intent.split(/[.!?]/)[0]?.slice(0, 120) || intent, instructions: `${draft.instructions ? `${draft.instructions}\n\n` : ""}${intent}`, revision: draft.revision + 1 }; }
  async preflight(draft: BuilderDraftView): Promise<readonly PreflightRow[]> { const ok = Boolean(draft.name.trim() && draft.instructions.trim()); return ["Instructions", "Model", "Skills", "Apps", "MCP", "Knowledge", "Memory", "Runtime", "Policy", "Budget", "Evals", "Outputs"].map((domain) => ({ domain, status: ok ? "passed" as const : domain === "Instructions" ? "failed" as const : "pending" as const, detail: ok ? "Pinned and available" : domain === "Instructions" ? "Name and instructions are required" : "Waiting for required fields" })); }
  async test(draft: BuilderDraftView, input: string): Promise<string> { if (!draft.instructions.trim() || !input.trim()) throw new Error("Instructions and a test input are required."); return `Test completed with ${draft.model}. The run used revision ${draft.revision}, requested approval for consequential tools, and produced a reviewable draft.`; }
  async publish(draft: BuilderDraftView): Promise<{ version: string; contentHash: string }> { if (!draft.name.trim()) throw new Error("Complete preflight before publishing."); return { version: "1.0.0", contentHash: "sha256:preview-only" }; }
  async search(): Promise<readonly DirectoryAgent[]> { return []; }
  async favorite(): Promise<void> { return; }
}
