export type BuilderTab = "instructions" | "model" | "capabilities" | "context" | "runtime" | "permissions" | "budget" | "evals";
export type BuilderStatus = "editing" | "testing" | "ready" | "publishing" | "published" | "failed";
export interface BuilderDraftView { readonly id: string; readonly name: string; readonly description: string; readonly instructions: string; readonly model: string; readonly skills: readonly string[]; readonly apps: readonly string[]; readonly mcp: readonly string[]; readonly knowledge: readonly string[]; readonly memory: readonly string[]; readonly runtime: readonly string[]; readonly permissions: readonly string[]; readonly budget: string; readonly evals: readonly string[]; readonly revision: number; }
export interface PreflightRow { readonly domain: string; readonly status: "passed" | "warning" | "failed" | "pending"; readonly detail: string; }
export interface DirectoryAgent { readonly id: string; readonly name: string; readonly description: string; readonly category: string; readonly version: string; readonly audience: string; readonly favorite: boolean; readonly runs: number; readonly uniqueUsers: number; }
export interface BuilderState { readonly draft: BuilderDraftView; readonly status: BuilderStatus; readonly tab: BuilderTab; readonly preflight: readonly PreflightRow[]; readonly testOutput?: string; readonly error?: string; }
export const BUILDER_TABS: readonly { id: BuilderTab; label: string }[] = [
  { id: "instructions", label: "Instructions" }, { id: "model", label: "Model" }, { id: "capabilities", label: "Skills, apps & MCP" }, { id: "context", label: "Knowledge & memory" }, { id: "runtime", label: "Runtime" }, { id: "permissions", label: "Permissions" }, { id: "budget", label: "Budget" }, { id: "evals", label: "Evals" },
];
export const EMPTY_DRAFT: BuilderDraftView = { id: "draft.new", name: "", description: "", instructions: "", model: "Standard model policy", skills: [], apps: [], mcp: [], knowledge: [], memory: ["Project memory"], runtime: ["Core", "Documents"], permissions: ["Read tools: allow", "Consequential tools: ask"], budget: "$5.00 per run", evals: ["Department smoke suite"], revision: 1 };
