from __future__ import annotations

from typing import Awaitable, Callable, Literal, Protocol

from fastapi import Request

from .models import BillingPrincipal, BillingStatus, EntitlementDecision, SubscriptionRecord, VerifiedStripeEvent


class BillingRepository(Protocol):
    async def begin_event(self, event: VerifiedStripeEvent) -> Literal["accepted", "duplicate"]: ...
    async def complete_event(self, event_id: str) -> None: ...
    async def fail_event(self, event_id: str, reason: str) -> None: ...
    async def get_subscription(self, organization_id: str) -> SubscriptionRecord | None: ...
    async def save_subscription(self, value: SubscriptionRecord) -> None: ...
    async def save_entitlement(self, value: EntitlementDecision) -> None: ...
    async def get_status(self, organization_id: str) -> BillingStatus: ...


class CheckoutPort(Protocol):
    async def create_checkout(self, *, organization_id: str, quantity: int, price_id: str, success_url: str, cancel_url: str, idempotency_key: str) -> str: ...


class PortalPort(Protocol):
    async def create_portal(self, *, organization_id: str, return_url: str) -> str: ...


class MembershipPort(Protocol):
    async def count_billable_members(self, organization_id: str) -> int: ...


class SeatQuantityPort(Protocol):
    async def set_quantity(self, *, subscription_id: str, quantity: int, idempotency_key: str) -> None: ...


class TelemetryPort(Protocol):
    def counter(self, name: str, value: int = 1, **attributes: str) -> None: ...
    def error(self, error: Exception, **attributes: str) -> None: ...


PrincipalResolver = Callable[[Request], Awaitable[BillingPrincipal]]
