from __future__ import annotations

from datetime import datetime
from typing import Protocol

from src.runtime.models import ActualCost, DurableEvent, Lease, RuntimeCheckpoint, RuntimeRun, StoredOutput

from .models import (
    AdapterCommand, EventStream, InvocationBrokerSession, InvocationRequest,
    RunControl, SandboxHandle, SandboxSpec, SingleUseInvocationToken,
)


class WorkerPersistence(Protocol):
    async def claim_one(self, *, worker_id: str, lease_expires_at: datetime) -> Lease | None: ...
    async def control(self, lease: Lease) -> RunControl: ...
    async def append_event(self, lease: Lease, event: DurableEvent) -> DurableEvent: ...
    async def heartbeat(self, lease: Lease, *, lease_expires_at: datetime) -> bool: ...
    async def write_checkpoint(self, lease: Lease, checkpoint: RuntimeCheckpoint) -> None: ...
    async def suspend_for_approval(
        self, lease: Lease, checkpoint: RuntimeCheckpoint, *, approval_id: str,
        operation: str, argument_summary: dict, expires_at: datetime | None,
    ) -> None: ...
    async def complete_success(
        self, lease: Lease, *, output: StoredOutput, costs: tuple[ActualCost, ...]
    ) -> None: ...
    async def complete_cancellation(self, lease: Lease, *, propagation: dict) -> None: ...
    async def record_failure(
        self, lease: Lease, *, failure_class: str, detail: dict, retryable: bool
    ) -> None: ...
    async def release(self, lease: Lease, *, reason: str) -> None: ...
    async def reconcile_expired(self, *, now: datetime) -> list[str]: ...
    async def terminal_state(self, run_id: str) -> str | None: ...


class CapabilityIssuer(Protocol):
    async def open_session(
        self, run: RuntimeRun, *, lease_id: str,
        allowed_invocations: dict[str, tuple[str, ...]],
    ) -> InvocationBrokerSession: ...


class InvocationBroker(Protocol):
    async def mint_once(
        self, session: InvocationBrokerSession, request: InvocationRequest
    ) -> SingleUseInvocationToken: ...


class SandboxLifecycle(Protocol):
    async def create_or_restore(self, spec: SandboxSpec) -> SandboxHandle: ...
    async def launch(self, handle: SandboxHandle, command: AdapterCommand) -> EventStream: ...
    async def cancel(self, handle: SandboxHandle) -> None: ...
    async def terminate(self, handle: SandboxHandle) -> None: ...
    async def reconcile(self, *, active_run_ids: frozenset[str]) -> list[str]: ...


class AdapterCommandFactory(Protocol):
    def build(
        self, lease: Lease, *, broker: InvocationBrokerSession,
        checkpoint: RuntimeCheckpoint | None,
    ) -> AdapterCommand: ...
