export type McpScope = "organization" | "project" | "agent";
export type McpHealth = "unknown" | "healthy" | "degraded" | "unhealthy" | "revoked" | "disconnected";
export interface McpToolSnapshot { readonly name: string; readonly input_schema: Record<string, unknown>; readonly output_schema?: Record<string, unknown>; readonly digest: string; }
export interface McpManifest { readonly schema_version: "1.0"; readonly id: `mcp.${string}`; readonly version: string; readonly transport: "stdio" | "streamable_http" | "sse"; readonly auth: "none" | "credential_reference" | "oauth_connection_reference"; readonly credential_reference_type?: string; readonly capability_ttl_seconds: number; readonly tools: readonly McpToolSnapshot[]; }
export interface McpBinding { readonly id: string; readonly server_id: string; readonly scope: McpScope; readonly scope_id: string; readonly status: "pending_approval" | "approved" | "revoked" | "disconnected"; }
export interface CapabilityCache { readonly server_id: string; readonly manifest_version: string; readonly captured_at: string; readonly expires_at: string; readonly digest: string; readonly tools: readonly McpToolSnapshot[]; }
export type SchemaDiff = "safe" | "review" | "breaking";
export function assertMcpManifest(manifest: McpManifest): McpManifest { if (manifest.schema_version !== "1.0" || !/^mcp\.[a-z0-9._-]+$/.test(manifest.id) || !manifest.version || !Number.isInteger(manifest.capability_ttl_seconds) || manifest.capability_ttl_seconds <= 0 || manifest.tools.some((tool) => !tool.name || !tool.digest)) throw new Error("invalid MCP manifest"); if (manifest.auth === "credential_reference" && !manifest.credential_reference_type) throw new Error("credential-reference MCP requires a reference type"); return Object.freeze(manifest); }
export function classifySchemaDiff(before: McpToolSnapshot, after: McpToolSnapshot): SchemaDiff { if (before.name !== after.name) return "breaking"; const a = JSON.stringify(before.input_schema); const b = JSON.stringify(after.input_schema); if (a === b && before.digest === after.digest) return "safe"; const oldRequired = Array.isArray((before.input_schema as { required?: unknown }).required) ? (before.input_schema as { required: string[] }).required : []; const newRequired = Array.isArray((after.input_schema as { required?: unknown }).required) ? (after.input_schema as { required: string[] }).required : []; return newRequired.some((x) => !oldRequired.includes(x)) ? "breaking" : "review"; }
export function cacheIsFresh(cache: CapabilityCache, now: string): boolean { return cache.expires_at > now; }
export function transitionMcpBinding(binding: McpBinding, action: "approve" | "disconnect" | "revoke"): McpBinding { if (binding.status === "revoked" && action !== "revoke") throw new Error("revoked MCP binding cannot be reactivated"); return Object.freeze({ ...binding, status: action === "approve" ? "approved" : action === "disconnect" ? "disconnected" : "revoked" }); }
export function availableMcpTools(manifest: McpManifest, binding: McpBinding | undefined, cache: CapabilityCache | undefined, now: string): readonly McpToolSnapshot[] { assertMcpManifest(manifest); if (!binding || binding.server_id !== manifest.id || binding.status !== "approved" || !cache || cache.server_id !== manifest.id || !cacheIsFresh(cache, now)) return Object.freeze([]); return Object.freeze(cache.tools); }
export function mcpDiscovery(manifests: readonly McpManifest[], bindings: readonly McpBinding[], caches: readonly CapabilityCache[], now: string): readonly { readonly id: string; readonly state: string; readonly intent: "browse" | "attach" }[] { return Object.freeze(manifests.map((m) => ({ id: m.id, intent: "attach" as const, state: availableMcpTools(m, bindings.find((b) => b.server_id === m.id), caches.find((c) => c.server_id === m.id), now).length ? "ready" : "unavailable" }))); }
