export type RiskClass = "read" | "write" | "destructive" | "financial_regulated" | "admin";
export type EffectScope = "none" | "external" | "organization" | "project" | "personal";
export type PolicyScope = "organization" | "project" | "agent" | "user";
export type Decision = "allow" | "ask" | "deny";
export interface ToolDefinition { readonly id: `tool.${string}`; readonly version: string; readonly risk: RiskClass; readonly effects: EffectScope; readonly resource_scopes: readonly string[]; readonly idempotency: "required" | "supported" | "none"; readonly credential_mode: "none" | "connection_reference" | "derived_capability"; readonly redact_paths: readonly string[]; }
export interface PolicyGrant { readonly id: string; readonly scope: PolicyScope; readonly scope_id: string; readonly tool_id: string | "*"; readonly decision: Decision; readonly max_calls?: number; readonly max_concurrency?: number; readonly max_cost_cents?: number; readonly expires_at?: string; }
export interface Approval { readonly id: string; readonly run_id: string; readonly tool_id: string; readonly status: "requested" | "approved" | "denied" | "expired"; readonly requested_at: string; readonly expires_at: string; readonly requested_by: string; readonly decided_by?: string; readonly decision_at?: string; readonly argument_preview: Record<string, unknown>; }
export interface PolicyContext { readonly organization_id: string; readonly project_id?: string; readonly agent_id: string; readonly user_id: string; readonly now: string; readonly current_calls?: number; readonly current_concurrency?: number; readonly current_cost_cents?: number; }
export interface ToolDecision { readonly decision: Decision; readonly reason: string; readonly approval_required: boolean; }
const rank: Record<PolicyScope, number> = { organization: 0, project: 1, agent: 2, user: 3 };
export function assertToolDefinition(tool: ToolDefinition): ToolDefinition { if (!/^tool\.[a-z0-9._-]+$/.test(tool.id) || !tool.version || !tool.resource_scopes.length || tool.credential_mode === undefined || !["read", "write", "destructive", "financial_regulated", "admin"].includes(tool.risk)) throw new Error("invalid tool definition"); if (tool.credential_mode === "connection_reference" && tool.effects === "none" && tool.resource_scopes.length === 0) throw new Error("credentialed tool requires a resource scope"); return Object.freeze(tool); }
export function resolveToolPolicy(tool: ToolDefinition | undefined, grants: readonly PolicyGrant[], ctx: PolicyContext, approval?: Approval): ToolDecision {
  if (!tool) return { decision: "deny", reason: "Unknown tools are denied.", approval_required: false }; assertToolDefinition(tool);
  const applicable = grants.filter((g) => (g.tool_id === "*" || g.tool_id === tool.id) && (!g.expires_at || g.expires_at > ctx.now) && ((g.scope === "organization" && g.scope_id === ctx.organization_id) || (g.scope === "project" && g.scope_id === ctx.project_id) || (g.scope === "agent" && g.scope_id === ctx.agent_id) || (g.scope === "user" && g.scope_id === ctx.user_id)));
  if (applicable.some((g) => g.decision === "deny")) return { decision: "deny", reason: "An applicable deny grant takes precedence.", approval_required: false };
  const selected = [...applicable].sort((a, b) => rank[b.scope] - rank[a.scope]).find((g) => g.decision !== "deny");
  if (!selected) return { decision: "deny", reason: "No least-privilege grant exists.", approval_required: false };
  if ((selected.max_calls !== undefined && (ctx.current_calls ?? 0) >= selected.max_calls) || (selected.max_concurrency !== undefined && (ctx.current_concurrency ?? 0) >= selected.max_concurrency) || (selected.max_cost_cents !== undefined && (ctx.current_cost_cents ?? 0) >= selected.max_cost_cents)) return { decision: "deny", reason: "A run budget or concurrency bound is exhausted.", approval_required: false };
  const approved = approval?.status === "approved" && approval.tool_id === tool.id && approval.expires_at > ctx.now;
  const consequential = tool.risk !== "read" || selected.decision === "ask";
  return consequential && !approved ? { decision: "ask", reason: "Approval is required for this consequential tool call.", approval_required: true } : { decision: "allow", reason: "Least-privilege grant permits this call.", approval_required: false };
}
export function redactArguments(value: unknown, paths: readonly string[]): unknown { const copy = JSON.parse(JSON.stringify(value)) as Record<string, unknown>; for (const path of paths) { let target: Record<string, unknown> | undefined = copy; const bits = path.split("."); for (const part of bits.slice(0, -1)) target = target && typeof target[part] === "object" ? target[part] as Record<string, unknown> : undefined; const final = bits.at(-1); if (target && final !== undefined && final in target) target[final] = "[REDACTED]"; } return copy; }
export interface CapabilityInput { readonly tool: ToolDefinition; readonly grants: readonly PolicyGrant[]; readonly app_connection?: { readonly ownership: "organization" | "project" | "user"; readonly owner_id: string; readonly status: "connected" | "revoked"; readonly explicitly_attached?: boolean; readonly shared_allowed?: boolean }; }
export function projectAllowedTools(inputs: readonly CapabilityInput[], ctx: PolicyContext, shared_agent: boolean): readonly ToolDefinition[] { return Object.freeze(inputs.flatMap((input) => { const c = input.app_connection; if (c?.status === "revoked" || (shared_agent && c?.ownership === "user" && (!c.explicitly_attached || !c.shared_allowed))) return []; return resolveToolPolicy(input.tool, input.grants, ctx).decision === "allow" ? [input.tool] : []; })); }
export interface ResolverInput { readonly agent: { readonly id: string; readonly shared: boolean; readonly allowed_capabilities: readonly string[] }; readonly installed_skills: readonly { readonly id: string; readonly state: "installed" | "review_required"; readonly required_capabilities: readonly string[]; readonly tool_inputs: readonly CapabilityInput[] }[]; readonly native_tools: readonly CapabilityInput[]; readonly app_tools: readonly CapabilityInput[]; readonly mcp_tools: readonly CapabilityInput[]; readonly approvals: readonly Approval[]; readonly context: PolicyContext; }
export interface ResolvedCapabilitySet { readonly agent_id: string; readonly capabilities: readonly string[]; readonly tools: readonly { readonly id: string; readonly version: string; readonly risk: RiskClass; readonly approval_required: boolean }[]; readonly withheld: readonly { readonly id: string; readonly reason: string }[]; }
/** The sole run projection. It does not return credential references or connections. */
export function resolveCapabilities(input: ResolverInput): ResolvedCapabilitySet {
  const capability = new Set(input.agent.allowed_capabilities); const tools: { id: string; version: string; risk: RiskClass; approval_required: boolean }[] = []; const withheld: { id: string; reason: string }[] = []; const candidates = [...input.native_tools, ...input.app_tools, ...input.mcp_tools];
  for (const skill of input.installed_skills) { if (skill.state !== "installed") { withheld.push({ id: skill.id, reason: "Skill review is incomplete." }); continue; } if (skill.required_capabilities.every((v) => capability.has(v))) candidates.push(...skill.tool_inputs); else withheld.push({ id: skill.id, reason: "Skill capability requirements are not met." }); }
  for (const candidate of candidates) { const connection = candidate.app_connection; if (connection?.status === "revoked") { withheld.push({ id: candidate.tool.id, reason: "Connection is revoked." }); continue; } if (input.agent.shared && connection?.ownership === "user" && (!connection.explicitly_attached || !connection.shared_allowed)) { withheld.push({ id: candidate.tool.id, reason: "Personal connection is not explicitly shared with this agent." }); continue; } const approval = input.approvals.find((a) => a.tool_id === candidate.tool.id && a.run_id === input.context.agent_id); const decision = resolveToolPolicy(candidate.tool, candidate.grants, input.context, approval); if (decision.decision === "deny") withheld.push({ id: candidate.tool.id, reason: decision.reason }); else tools.push({ id: candidate.tool.id, version: candidate.tool.version, risk: candidate.tool.risk, approval_required: decision.approval_required }); }
  return Object.freeze({ agent_id: input.agent.id, capabilities: Object.freeze([...capability].sort()), tools: Object.freeze(tools.sort((a, b) => a.id.localeCompare(b.id))), withheld: Object.freeze(withheld.sort((a, b) => a.id.localeCompare(b.id))) });
}
