import { useCallback, useEffect, useMemo, useState } from "react";
import { DemoAutomationAdapter, EMPTY_AUTOMATION_DATA, type AutomationDashboardData, type AutomationUiAdapter } from "../../features/automations";
import "./automations.css";

type View="automations"|"history"|"failures"|"approvals";
const statusLabel=(value:string)=>value.replaceAll("_"," ");
export interface AutomationWorkspaceProps { readonly adapter?:AutomationUiAdapter; readonly initialData?:AutomationDashboardData; }
export function AutomationWorkspace({adapter:provided,initialData=EMPTY_AUTOMATION_DATA}:AutomationWorkspaceProps){
  const adapter=useMemo(()=>provided??new DemoAutomationAdapter(initialData),[provided,initialData]);const [data,setData]=useState(initialData);const [view,setView]=useState<View>("automations");const [busy,setBusy]=useState<string>();const [notice,setNotice]=useState("");const [error,setError]=useState("");
  const refresh=useCallback(async()=>setData(await adapter.load()),[adapter]);useEffect(()=>{void refresh().catch(e=>setError(e instanceof Error?e.message:"Unable to load automations."));},[refresh]);
  async function act(key:string,work:()=>Promise<void>){setBusy(key);setError("");setNotice("");try{await work();await refresh();}catch(e){setError(e instanceof Error?e.message:"The action failed.");}finally{setBusy(undefined);}}
  const failed=data.runs.filter(run=>run.state==="failed"||run.state==="dead_letter");const pending=data.approvals.filter(item=>item.status==="pending");const live=Object.values(data.integrations).every(value=>value==="connected");
  return <main className="au-page"><header className="au-header"><div><p className="au-kicker">Automation control plane</p><h1>Recurring work,<br/><span>with receipts.</span></h1><p className="au-intro">Inspect the exact version, trigger, budget, approvals, and delivery state for every repeatable task.</p></div><div className="au-readiness" data-live={live}><span className="au-signal"/><div><strong>{live?"Live integrations connected":"Reference adapters only"}</strong><p>{live?"Scheduler, runtime, delivery, and persistence report connected.":"No live scheduler, Composio event, runtime job, or external notification is claimed by this screen."}</p></div></div></header>
  <nav className="au-nav" aria-label="Automation views">{(["automations","history","failures","approvals"] as const).map(item=><button type="button" className={view===item?"is-active":""} onClick={()=>setView(item)} key={item}>{item}<span>{item==="automations"?data.automations.length:item==="history"?data.runs.length:item==="failures"?failed.length:pending.length}</span></button>)}</nav>
  {notice&&<div className="au-notice" role="status">{notice}</div>}{error&&<div className="au-error" role="alert">{error}</div>}
  {view==="automations"&&<section className="au-list" aria-label="Automation definitions">{data.automations.length===0?<Empty title="No automation definitions" body="Publish an immutable automation version through a connected API before enabling a trigger."/>:data.automations.map((automation,index)=><article className="au-row" key={automation.id} style={{"--delay":`${index*55}ms`} as React.CSSProperties}><div className="au-row-index">{String(index+1).padStart(2,"0")}</div><div className="au-row-main"><div className="au-title-line"><h2>{automation.name}</h2><span className={`au-state au-state--${automation.state}`}>{statusLabel(automation.state)}</span></div><p>{automation.trigger}</p><dl><div><dt>Immutable version</dt><dd>{automation.version}</dd></div><div><dt>Run identity</dt><dd>{automation.principal}</dd></div><div><dt>Next run</dt><dd>{automation.nextRun??"Not scheduled"}</dd></div><div><dt>Budget</dt><dd>${(automation.costCents/100).toFixed(2)} / ${(automation.costLimitCents/100).toFixed(2)}</dd></div></dl></div><div className="au-row-actions"><button type="button" disabled={busy===automation.id} onClick={()=>act(automation.id,async()=>{if(automation.state==="active"){await adapter.pause(automation.id);}else{await adapter.resume(automation.id);}setNotice(automation.state==="active"?"Automation paused and future schedule removed.":"Resume requested. Live scheduling still depends on a connected scheduler adapter.");})}>{automation.state==="active"?"Pause":"Resume"}</button><button type="button" disabled={busy===`test:${automation.id}`} onClick={()=>act(`test:${automation.id}`,async()=>{await adapter.test(automation.id,{source:"ui"});setNotice("Test completed through the configured adapter; external destinations were suppressed.");})}>Test safely</button></div></article>)}</section>}
  {view==="history"&&<RunList runs={data.runs} empty="No durable run history is available."/>}
  {view==="failures"&&<section className="au-panel"><header><div><p className="au-kicker">Recovery queue</p><h2>Failure inbox</h2></div><p>Retry creates a new bounded attempt; it does not overwrite the original failure.</p></header>{failed.length===0?<Empty title="No failed executions" body="Failures and dead letters will remain visible here after terminal handling."/>:<RunList runs={failed} empty="" onRetry={runId=>act(`retry:${runId}`,async()=>{await adapter.retry(runId);setNotice("Retry requested through the configured adapter.");})}/>}</section>}
  {view==="approvals"&&<section className="au-panel"><header><div><p className="au-kicker">Consequence boundary</p><h2>Approval inbox</h2></div><p>External actions remain blocked until a current approval is durably recorded.</p></header>{pending.length===0?<Empty title="No pending approvals" body="Approval requests will show the destination and expiry before an action can continue."/>:<div className="au-approvals">{pending.map(item=><article key={item.id}><div><strong>{item.automationName}</strong><p>{item.action}</p><small>Expires {item.expiresAt}</small></div><div><button onClick={()=>act(`deny:${item.id}`,()=>adapter.resolveApproval(item.id,"denied"))}>Deny</button><button className="au-primary" onClick={()=>act(`approve:${item.id}`,()=>adapter.resolveApproval(item.id,"approved"))}>Approve once</button></div></article>)}</div>}</section>}
  <footer className="au-integrations"><span>Adapter truth</span>{Object.entries(data.integrations).map(([name,state])=><div key={name}><i className={state==="connected"?"is-connected":""}/><strong>{name}</strong><small>{statusLabel(state)}</small></div>)}</footer></main>;
}
function Empty({title,body}:{title:string;body:string}){return <div className="au-empty"><span aria-hidden="true">00</span><div><strong>{title}</strong><p>{body}</p></div></div>}
function RunList({runs,empty,onRetry}:{runs:AutomationDashboardData["runs"];empty:string;onRetry?:(id:string)=>void}){if(!runs.length)return <Empty title="No executions" body={empty}/>;return <div className="au-runs">{runs.map(run=><article key={run.id}><span className={`au-state au-state--${run.state}`}>{statusLabel(run.state)}</span><div><strong>{run.trigger}</strong><p>{run.detail}</p></div><dl><div><dt>Version</dt><dd>{run.version}</dd></div><div><dt>Attempt</dt><dd>{run.attempt}</dd></div><div><dt>Cost</dt><dd>${(run.costCents/100).toFixed(2)}</dd></div><div><dt>Started</dt><dd>{run.startedAt}</dd></div></dl>{onRetry&&<button type="button" onClick={()=>onRetry(run.id)}>Retry</button>}</article>)}</div>}
