export type AppScope = "organization" | "project" | "user";
export type ConnectionState = "disconnected" | "connect_requested" | "connected" | "unhealthy" | "reconnect_required" | "revoked" | "deleted";
export interface AppAction { readonly id: string; readonly label: string; readonly risk: "read" | "write" | "destructive"; readonly version: string; }
export interface AppManifest { readonly schema_version: "1.0"; readonly id: `app.${string}`; readonly provider: "composio"; readonly toolkit: string; readonly toolkit_version: string; readonly label: string; readonly actions: readonly AppAction[]; readonly external_identity_mapping: "internal_actor_to_provider_entity"; }
export interface ConnectLinkRequest { readonly request_id: string; readonly app_id: string; readonly owner_scope: AppScope; readonly owner_id: string; readonly return_url: string; readonly required_actions: readonly string[]; readonly session_tool_allowlist: readonly string[]; readonly permission_preview: readonly string[]; }
export interface ConnectLinkReturn { readonly request_id: string; readonly status: "connected" | "cancelled" | "failed"; readonly connected_account_reference?: string; readonly error_code?: string; }
export interface AppConnection { readonly id: string; readonly app_id: string; readonly owner_scope: AppScope; readonly owner_id: string; readonly connected_account_reference?: `connection-ref.${string}`; readonly status: ConnectionState; readonly allowed_actions: readonly string[]; readonly health_checked_at?: string; readonly audit: readonly { readonly at: string; readonly action: string; readonly actor_id: string }[]; }
export const HIGH_VALUE_APPS: readonly AppManifest[] = Object.freeze([
  { schema_version: "1.0", id: "app.google-drive", provider: "composio", toolkit: "GOOGLEDRIVE", toolkit_version: "pinned-1", label: "Google Drive", actions: [{ id: "files.search", label: "Search files", risk: "read", version: "1" }, { id: "files.create", label: "Create file", risk: "write", version: "1" }], external_identity_mapping: "internal_actor_to_provider_entity" },
  { schema_version: "1.0", id: "app.notion", provider: "composio", toolkit: "NOTION", toolkit_version: "pinned-1", label: "Notion", actions: [{ id: "search", label: "Search pages", risk: "read", version: "1" }, { id: "create-page", label: "Create page", risk: "write", version: "1" }], external_identity_mapping: "internal_actor_to_provider_entity" },
  { schema_version: "1.0", id: "app.slack", provider: "composio", toolkit: "SLACK", toolkit_version: "pinned-1", label: "Slack", actions: [{ id: "search", label: "Search messages", risk: "read", version: "1" }, { id: "send", label: "Send message", risk: "write", version: "1" }], external_identity_mapping: "internal_actor_to_provider_entity" },
  { schema_version: "1.0", id: "app.microsoft-365", provider: "composio", toolkit: "MICROSOFT365", toolkit_version: "pinned-1", label: "Microsoft 365 / SharePoint", actions: [{ id: "search", label: "Search content", risk: "read", version: "1" }, { id: "create", label: "Create content", risk: "write", version: "1" }], external_identity_mapping: "internal_actor_to_provider_entity" },
  { schema_version: "1.0", id: "app.linear", provider: "composio", toolkit: "LINEAR", toolkit_version: "pinned-1", label: "Linear", actions: [{ id: "issues.list", label: "List issues", risk: "read", version: "1" }, { id: "issues.create", label: "Create issue", risk: "write", version: "1" }], external_identity_mapping: "internal_actor_to_provider_entity" },
]);
export function assertAppManifest(manifest: AppManifest): AppManifest { if (manifest.schema_version !== "1.0" || !/^app\.[a-z0-9._-]+$/.test(manifest.id) || manifest.provider !== "composio" || !manifest.toolkit || !manifest.toolkit_version || !manifest.actions.length || new Set(manifest.actions.map((a) => a.id)).size !== manifest.actions.length) throw new Error("invalid app manifest"); if (manifest.actions.some((a) => !a.version || !a.label)) throw new Error("app actions must be versioned and labeled"); return Object.freeze(manifest); }
export function createConnectLinkRequest(manifest: AppManifest, owner_scope: AppScope, owner_id: string, actions: readonly string[]): ConnectLinkRequest { assertAppManifest(manifest); const known = new Set(manifest.actions.map((a) => a.id)); if (!actions.length || actions.some((a) => !known.has(a))) throw new Error("requested action is not pinned in the toolkit manifest"); return Object.freeze({ request_id: `connect.${manifest.id}.${owner_id}`, app_id: manifest.id, owner_scope, owner_id, return_url: "/connections/return", required_actions: Object.freeze([...actions]), session_tool_allowlist: Object.freeze([...actions]), permission_preview: Object.freeze(actions.map((a) => manifest.actions.find((x) => x.id === a)!.label)) }); }
export function applyConnectReturn(request: ConnectLinkRequest, result: ConnectLinkReturn, actor_id: string, at: string): AppConnection { if (request.request_id !== result.request_id) throw new Error("Connect Link correlation mismatch"); const connected = result.status === "connected" && result.connected_account_reference; return Object.freeze({ id: `app-connection.${request.request_id}`, app_id: request.app_id, owner_scope: request.owner_scope, owner_id: request.owner_id, connected_account_reference: connected ? `connection-ref.${result.connected_account_reference}` : undefined, status: connected ? "connected" : result.status === "cancelled" ? "disconnected" : "reconnect_required", allowed_actions: request.required_actions, health_checked_at: at, audit: Object.freeze([{ at, action: connected ? "connected" : result.status, actor_id }]) }); }
export function transitionConnection(connection: AppConnection, action: "health_ok" | "health_failed" | "reconnect" | "revoke" | "delete", actor_id: string, at: string): AppConnection { if (connection.status === "deleted") throw new Error("deleted connection cannot transition"); const status: ConnectionState = action === "health_ok" ? "connected" : action === "health_failed" ? "unhealthy" : action === "reconnect" ? "reconnect_required" : action === "revoke" ? "revoked" : "deleted"; return Object.freeze({ ...connection, status, connected_account_reference: action === "revoke" || action === "delete" ? undefined : connection.connected_account_reference, health_checked_at: at, audit: Object.freeze([...connection.audit, { at, action, actor_id }]) }); }
export function appDiscovery(manifests: readonly AppManifest[], connections: readonly AppConnection[]): readonly { readonly id: string; readonly state: string; readonly intent: "browse" | "attach" }[] { return Object.freeze(manifests.map((m) => ({ id: m.id, state: connections.find((c) => c.app_id === m.id)?.status ?? "disconnected", intent: "attach" as const }))); }
