import assert from "node:assert/strict";import test from "node:test";
import { BillingEntitlementService, DISABLED_BILLING_CONFIGURATION, deriveEntitlement, reconcileSeats, type BillingRepository, type OrganizationEntitlement, type OrganizationSubscription, type SeatSnapshot, type VerifiedBillingEvent } from "../src/index.ts";
class Repo implements BillingRepository {events=new Set<string>();failed=new Map<string,string>();subscription?:OrganizationSubscription;entitlement?:OrganizationEntitlement;snapshot?:SeatSnapshot;async beginEvent(e:VerifiedBillingEvent){if(this.events.has(e.id))return "duplicate" as const;this.events.add(e.id);return "accepted" as const;}async completeEvent(){}async failEvent(id:string,reason:string){this.failed.set(id,reason);}async getSubscription(){return this.subscription;}async saveSubscription(v:OrganizationSubscription){this.subscription=v;}async saveEntitlement(v:OrganizationEntitlement){this.entitlement=v;}async saveSeatSnapshot(v:SeatSnapshot){this.snapshot=v;}}
const clock={now:()=>new Date("2026-07-11T00:00:00Z")};
const event=(id:string,created:number,status="active"):VerifiedBillingEvent=>({id,type:"customer.subscription.updated",created,livemode:false,object:{id:"sub_1",customer:"cus_1",status,quantity:3,metadata:{organization_id:"org_1"}}});
test("verified subscription grants server-derived entitlement and duplicate is inert",async()=>{const repo=new Repo();const service=new BillingEntitlementService(repo,clock,DISABLED_BILLING_CONFIGURATION);assert.equal(await service.consumeVerifiedEvent(event("evt_1",10)),"applied");assert.equal(repo.entitlement?.state,"enabled");assert.equal(await service.consumeVerifiedEvent(event("evt_1",10)),"duplicate");});
test("older provider event cannot roll state backward",async()=>{const repo=new Repo();const service=new BillingEntitlementService(repo,clock,DISABLED_BILLING_CONFIGURATION);await service.consumeVerifiedEvent(event("new",20));assert.equal(await service.consumeVerifiedEvent(event("old",10,"canceled")),"ignored_stale");assert.equal(repo.subscription?.status,"active");});
test("unpaid and missing subscriptions never grant access",()=>{assert.equal(deriveEntitlement(undefined,clock.now(),0).state,"disabled");assert.equal(deriveEntitlement({...event("x",1,"unpaid").object,organization_id:"org_1",customer_id:"cus_1",subscription_id:"sub_1",status:"unpaid",quantity:1,provider_event_created:1,cancel_at_period_end:false} as OrganizationSubscription,clock.now(),0).state,"disabled");});
test("seat reconciliation is dry-run unless apply is explicit",async()=>{const repo=new Repo();let updates=0;const subscription:OrganizationSubscription={organization_id:"org_1",customer_id:"c",subscription_id:"s",status:"active",quantity:2,provider_event_created:1,cancel_at_period_end:false};const snapshot=await reconcileSeats({organization_id:"org_1",subscription,memberships:{countBillableMembers:async()=>4},quantities:{setQuantity:async()=>{updates++;}},repository:repo,clock,apply:false});assert.equal(snapshot.matches,false);assert.equal(updates,0);});
