import type { Actor, AgentCatalogPort, AgentConfig, AgentRecord, AgentRegistryPersistencePort, AgentRuntimeResolutionPort, AgentVersion, Audience, Deployment, DeploymentTarget, DirectoryEntry, EvalRunnerPort, MutableAgentDraft, PublicationRequest, RunAgentResolution, ValidationDomain, ValidationIssue, ValidationReport } from "./contracts.ts";

const encoder = new TextEncoder();
function stable(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stable).join(",")}]`; if (value && typeof value === "object") return `{${Object.entries(value as Record<string, unknown>).filter(([, v]) => v !== undefined).sort(([a], [b]) => a.localeCompare(b)).map(([k, v]) => `${JSON.stringify(k)}:${stable(v)}`).join(",")}}`; return JSON.stringify(value); }
export async function digest(value: unknown): Promise<`sha256:${string}`> { const bytes = await crypto.subtle.digest("SHA-256", encoder.encode(stable(value))); return `sha256:${[...new Uint8Array(bytes)].map((v) => v.toString(16).padStart(2, "0")).join("")}`; }
const freeze = <T>(value: T): Readonly<T> => Object.freeze(value);
function canBuild(actor: Actor): boolean { return ["owner", "admin", "builder"].includes(actor.role); }
function canPublish(actor: Actor, audience: Audience): boolean { return audience === "private" ? canBuild(actor) || actor.role === "member" : canBuild(actor); }
function assertOrg(actor: Actor, org: string): void { if (actor.organization_id !== org) throw new Error("permission_denied: cross-organization access"); }

export interface RegistryPolicy { readonly require_organization_publication_approval: boolean; readonly unresolved_placeholder_pattern?: RegExp; }
export class AgentRegistryService implements AgentRuntimeResolutionPort {
  private readonly store: AgentRegistryPersistencePort; private readonly catalog: AgentCatalogPort; private readonly evals: EvalRunnerPort; private readonly policy: RegistryPolicy;
  constructor(store: AgentRegistryPersistencePort, catalog: AgentCatalogPort, evals: EvalRunnerPort, policy: RegistryPolicy) { this.store = store; this.catalog = catalog; this.evals = evals; this.policy = policy; }

  async create(actor: Actor, config: AgentConfig, now: string, id = `agent.${crypto.randomUUID()}`): Promise<MutableAgentDraft> {
    if (!canBuild(actor) && actor.role !== "member") throw new Error("permission_denied: role cannot create agents");
    const record: AgentRecord = freeze({ id, organization_id: actor.organization_id, owner_id: actor.id, state: "draft", created_at: now });
    const draft: MutableAgentDraft = freeze({ id: `draft.${crypto.randomUUID()}`, agent_id: id, organization_id: actor.organization_id, owner_id: actor.id, revision: 1, state: "draft", config: structuredClone(config), updated_at: now });
    await this.store.createAgent(record, draft); return draft;
  }
  async updateDraft(actor: Actor, draft_id: string, expected_revision: number, config: AgentConfig, now: string): Promise<MutableAgentDraft> {
    const current = await this.requireDraft(draft_id); assertOrg(actor, current.organization_id);
    if (actor.id !== current.owner_id && !canBuild(actor)) throw new Error("permission_denied: draft owner or builder required");
    const next = freeze({ ...current, revision: current.revision + 1, config: structuredClone(config), updated_at: now });
    await this.store.saveDraft(next, expected_revision); return next;
  }
  async conversationalProposal(actor: Actor, prompt: string, base: AgentConfig): Promise<AgentConfig> {
    if (!prompt.trim()) throw new Error("builder_prompt_required");
    const first = prompt.trim().split(/[.!?]/)[0]?.slice(0, 140) || base.description;
    return freeze({ ...structuredClone(base), description: first, instructions: `${base.instructions.trim()}\n\nBuilder intent:\n${prompt.trim()}` });
  }
  async preview(actor: Actor, draft_id: string, now: string): Promise<ValidationReport> {
    const draft = await this.requireDraft(draft_id); assertOrg(actor, draft.organization_id);
    const snapshots = await this.catalog.resolve(draft.config, actor); const eval_results = await this.evals.run(draft.config, actor);
    const issues: ValidationIssue[] = [];
    if (!draft.config.name.trim() || !draft.config.instructions.trim()) issues.push({ domain: "instructions", code: "required", severity: "error", message: "Name and instructions are required." });
    const placeholder = this.policy.unresolved_placeholder_pattern ?? /\{\{[^}]+\}\}|TODO|<fill-me>/i;
    if (placeholder.test(draft.config.instructions)) issues.push({ domain: "instructions", code: "unresolved_placeholder", severity: "error", message: "Instructions contain an unresolved placeholder." });
    for (const snapshot of snapshots) { for (const ref of snapshot.unavailable) issues.push({ domain: snapshot.domain, code: "unavailable", severity: "error", message: `${ref} is unavailable.`, subject: ref }); for (const error of snapshot.policy_errors) issues.push({ domain: snapshot.domain, code: "policy", severity: "error", message: error }); }
    this.localChecks(draft.config, issues);
    for (const result of eval_results) if (!result.passed) issues.push({ domain: "evals", code: "threshold_not_met", severity: "error", message: `${result.eval_id} scored ${result.score}.`, subject: result.eval_id });
    const dependency_digest = await digest(snapshots); const config_digest = await digest(draft.config);
    const report: ValidationReport = freeze({ id: `validation.${crypto.randomUUID()}`, draft_id, draft_revision: draft.revision, dependency_digest, config_digest, issues: freeze(issues), eval_results: freeze([...eval_results]), passed: !issues.some((i) => i.severity === "error"), validated_at: now });
    await this.store.saveReport(report); return report;
  }
  async requestPublication(actor: Actor, draft_id: string, target: DeploymentTarget, now: string): Promise<PublicationRequest | undefined> {
    const draft = await this.requireDraft(draft_id); assertOrg(actor, draft.organization_id); if (!canPublish(actor, target.audience)) throw new Error("permission_denied: publication role required");
    if (target.audience !== "organization_directory" || !this.policy.require_organization_publication_approval || actor.role === "owner" || actor.role === "admin") return undefined;
    const request = freeze({ id: `publication.${crypto.randomUUID()}`, draft_id, requester_id: actor.id, status: "pending" as const }); await this.store.savePublicationRequest(request); return request;
  }
  async decidePublication(actor: Actor, request_id: string, approved: boolean, now: string): Promise<PublicationRequest> {
    if (!["owner", "admin"].includes(actor.role)) throw new Error("permission_denied: admin approval required"); const current = await this.store.getPublicationRequest(request_id); if (!current || current.status !== "pending") throw new Error("publication_request_not_pending");
    const draft = await this.requireDraft(current.draft_id); assertOrg(actor, draft.organization_id);
    const next = freeze({ ...current, status: approved ? "approved" as const : "denied" as const, decided_by: actor.id, decided_at: now }); await this.store.savePublicationRequest(next); return next;
  }
  async publish(actor: Actor, draft_id: string, report_id: string, target: DeploymentTarget, release_notes: string, now: string, approval_id?: string): Promise<{ version: AgentVersion; deployment: Deployment }> {
    const draft = await this.requireDraft(draft_id); assertOrg(actor, draft.organization_id); if (!canPublish(actor, target.audience)) throw new Error("permission_denied: publication role required");
    const report = await this.store.getReport(report_id); if (!report || !report.passed || report.draft_id !== draft.id || report.draft_revision !== draft.revision) throw new Error("validation_required: current draft has not passed");
    if (await digest(draft.config) !== report.config_digest) throw new Error("hash_mismatch: draft content changed");
    const currentSnapshots = await this.catalog.resolve(draft.config, actor); if (await digest(currentSnapshots) !== report.dependency_digest) throw new Error("dependency_changed: preflight must be rerun");
    if (target.audience === "organization_directory" && this.policy.require_organization_publication_approval && !["owner", "admin"].includes(actor.role)) { const approval = approval_id ? await this.store.getPublicationRequest(approval_id) : undefined; if (!approval || approval.draft_id !== draft.id || approval.status !== "approved") throw new Error("approval_required: organization publication"); }
    const prior = await this.store.listVersions(draft.agent_id); const content_hash = await digest({ schema_version: "1.0", agent_id: draft.agent_id, ordinal: prior.length + 1, config: draft.config });
    const version: AgentVersion = freeze({ id: `agent-version.${content_hash.slice(7)}`, agent_id: draft.agent_id, organization_id: draft.organization_id, ordinal: prior.length + 1, state: "published", config: structuredClone(draft.config), content_hash, dependency_digest: report.dependency_digest, publisher_id: actor.id, validation_report_id: report.id, release_notes, created_at: now });
    await this.store.saveVersion(version); const deployment = await this.movePointer(actor, version, target, now); return { version, deployment };
  }
  async rollback(actor: Actor, deployment_id: string, version_id: string, expected_revision: number, now: string): Promise<Deployment> { if (!canBuild(actor)) throw new Error("permission_denied: rollback role required"); const deployment = await this.requireDeployment(deployment_id); assertOrg(actor, deployment.organization_id); if (deployment.revision !== expected_revision) throw new Error("revision_conflict"); const version = await this.store.getVersion(version_id); if (!version || version.agent_id !== deployment.agent_id || version.state === "deprecated") throw new Error("invalid_rollback_version"); return this.movePointer(actor, version, deployment.target, now, deployment); }
  async deprecate(actor: Actor, version_id: string, now: string): Promise<AgentVersion> { if (!canBuild(actor)) throw new Error("permission_denied: deprecation role required"); const current = await this.store.getVersion(version_id); if (!current) throw new Error("version_not_found"); assertOrg(actor, current.organization_id); if ((await this.store.listDeployments(current.agent_id)).some((d) => d.active_version_id === version_id)) throw new Error("active_version_cannot_be_deprecated"); const next = freeze({ ...current, state: "deprecated" as const, deprecated_at: now }); await this.store.saveVersion(next); return next; }
  async resolveForRun(deployment_id: string, actor: Actor, at: string): Promise<RunAgentResolution> { const deployment = await this.requireDeployment(deployment_id); assertOrg(actor, deployment.organization_id); this.assertAudience(actor, deployment.target); const version = await this.store.getVersion(deployment.active_version_id); if (!version || version.state !== "published" || version.content_hash !== await digest({ schema_version: "1.0", agent_id: version.agent_id, ordinal: version.ordinal, config: version.config })) throw new Error("version_integrity_failure"); await this.store.recordUsage(version.id, actor.id, at); return freeze({ agent_id: version.agent_id, agent_version_id: version.id, content_hash: version.content_hash, deployment_id: deployment.id, deployment_revision: deployment.revision, effective_config: structuredClone(version.config), resolved_at: at }); }
  async directory(actor: Actor, query = ""): Promise<readonly DirectoryEntry[]> { const records = await this.store.listAgents(actor.organization_id); const deployments = await this.store.listDeployments(); const out: DirectoryEntry[] = []; for (const agent of records) for (const deployment of deployments.filter((d) => d.agent_id === agent.id && this.visible(actor, d.target))) { const version = await this.store.getVersion(deployment.active_version_id); if (!version || version.state !== "published") continue; if (query && !`${version.config.name} ${version.config.description} ${version.config.category}`.toLowerCase().includes(query.toLowerCase())) continue; out.push({ agent, version, deployment, favorite: await this.store.isFavorite(actor.id, agent.id), ...(await this.store.usage(version.id)) }); } return freeze(out.sort((a, b) => Number(b.favorite) - Number(a.favorite) || a.version.config.name.localeCompare(b.version.config.name))); }
  async favorite(actor: Actor, agent_id: string, value: boolean): Promise<void> { const agent = await this.store.getAgent(agent_id); if (!agent) throw new Error("agent_not_found"); assertOrg(actor, agent.organization_id); await this.store.setFavorite(actor.id, agent_id, value); }
  private localChecks(config: AgentConfig, issues: ValidationIssue[]): void { const required: ValidationDomain[] = ["model", "skills", "apps", "mcp", "knowledge", "memory", "runtime", "policy", "budget", "evals", "outputs"]; void required; if (config.budget.max_cost_cents <= 0 || config.budget.max_tokens <= 0 || config.budget.max_concurrency <= 0 || config.budget.max_retries < 0) issues.push({ domain: "budget", code: "invalid_limit", severity: "error", message: "Budget limits must be positive and retries non-negative." }); if (config.runtime.wall_time_seconds <= 0 || config.runtime.cpu <= 0 || config.runtime.memory_mb < 256) issues.push({ domain: "runtime", code: "invalid_resources", severity: "error", message: "Runtime resources are outside safe bounds." }); if (!config.evals.length || config.evals.some((e) => !e.smoke_inputs.length || e.threshold < 0 || e.threshold > 1)) issues.push({ domain: "evals", code: "invalid_suite", severity: "error", message: "At least one valid eval with smoke inputs is required." }); for (const tool of config.tools) if (tool.risk !== "read" && tool.decision === "allow") issues.push({ domain: "policy", code: "approval_gap", severity: "error", message: `${tool.id} requires ask or deny.`, subject: tool.id }); if (config.memory_read_scopes.includes("user") && config.category !== "personal") issues.push({ domain: "memory", code: "personal_memory_shared", severity: "error", message: "Shared agents cannot implicitly read personal memory." }); }
  private async movePointer(actor: Actor, version: AgentVersion, target: DeploymentTarget, now: string, existing?: Deployment): Promise<Deployment> { const id = existing?.id ?? `deployment.${version.agent_id}.${target.audience}.${target.audience_ids.join("-") || "default"}`; const current = existing ?? await this.store.getDeployment(id); const deployment = freeze({ id, agent_id: version.agent_id, organization_id: version.organization_id, target: freeze({ audience: target.audience, audience_ids: freeze([...target.audience_ids]) }), active_version_id: version.id, revision: (current?.revision ?? 0) + 1, updated_by: actor.id, updated_at: now }); await this.store.saveDeployment(deployment, current?.revision); return deployment; }
  private visible(actor: Actor, target: DeploymentTarget): boolean { return target.audience === "organization_directory" || target.audience === "organization_link" || (target.audience === "private" && target.audience_ids.includes(actor.id)) || (target.audience === "team" && target.audience_ids.some((id) => actor.team_ids.includes(id))) || (target.audience === "selected_groups" && target.audience_ids.some((id) => actor.group_ids.includes(id))); }
  private assertAudience(actor: Actor, target: DeploymentTarget): void { if (!this.visible(actor, target) && target.audience !== "automation") throw new Error("permission_denied: deployment audience"); }
  private async requireDraft(id: string): Promise<MutableAgentDraft> { const value = await this.store.getDraft(id); if (!value) throw new Error("draft_not_found"); return value; }
  private async requireDeployment(id: string): Promise<Deployment> { const value = await this.store.getDeployment(id); if (!value) throw new Error("deployment_not_found"); return value; }
}
