import assert from "node:assert/strict";
import test from "node:test";
import { AgentRegistryService, InMemoryAgentRegistry, digest, type Actor, type AgentCatalogPort, type AgentConfig, type DependencySnapshot, type EvalRunnerPort } from "../src/index.ts";

const SHA = `sha256:${"1".repeat(64)}` as const;
const builder: Actor = { id: "user.builder", organization_id: "org.one", role: "builder", team_ids: ["team.ops"], group_ids: [] };
const member: Actor = { ...builder, id: "user.member", role: "member" };
const outsider: Actor = { ...builder, id: "user.outside", organization_id: "org.two" };
const config: AgentConfig = { name: "Operations", description: "Coordinates weekly work.", category: "operations", instructions: "Create bounded internal drafts.", model: { id: "model.standard", version: "1", digest: SHA }, skills: [], apps: [], mcp: [], knowledge_scopes: ["project.alpha"], memory_read_scopes: ["project"], memory_write_mode: "propose", tools: [{ id: "tool.email.send", version: "1", digest: SHA, risk: "write", decision: "ask" }], runtime: { image_digest: SHA, capability_packs: ["core"], network_allowlist: [], readable_paths: ["/workspace/input"], writable_paths: ["/workspace/output"], cpu: 1, memory_mb: 1024, wall_time_seconds: 300 }, budget: { max_cost_cents: 100, max_tokens: 10000, max_retries: 1, max_concurrency: 1 }, evals: [{ id: "eval.ops", version: "1", threshold: .8, smoke_inputs: ["Draft a checklist"] }], output_templates: [{ id: "output.brief", version: "1", digest: SHA }], approval_policy_ref: "policy.ask" };
class Catalog implements AgentCatalogPort { drift = false; async resolve(value: AgentConfig): Promise<readonly DependencySnapshot[]> { return [{ domain: "model", refs: [{ ...value.model, version: this.drift ? "2" : value.model.version }], unavailable: [], policy_errors: [] }, ...(["skills", "apps", "mcp", "knowledge", "memory", "runtime", "policy"] as const).map((domain) => ({ domain, refs: [], unavailable: [], policy_errors: [] }))]; } }
const evals: EvalRunnerPort = { async run(value) { return value.evals.map((e) => ({ eval_id: e.id, version: e.version, score: .95, passed: true, evidence_ref: "fixture://pass" })); } };
function harness(approval = false) { const store = new InMemoryAgentRegistry(); const catalog = new Catalog(); return { store, catalog, service: new AgentRegistryService(store, catalog, evals, { require_organization_publication_approval: approval }) }; }

test("publishes immutable content and resolves the exact deployed version", async () => { const { service } = harness(); const draft = await service.create(builder, config, "2026-07-11T00:00:00Z", "agent.ops"); const report = await service.preview(builder, draft.id, "2026-07-11T00:01:00Z"); assert.equal(report.passed, true); const { version, deployment } = await service.publish(builder, draft.id, report.id, { audience: "team", audience_ids: ["team.ops"] }, "first", "2026-07-11T00:02:00Z"); const run = await service.resolveForRun(deployment.id, builder, "2026-07-11T00:03:00Z"); assert.equal(run.agent_version_id, version.id); assert.equal(run.content_hash, version.content_hash); assert.deepEqual(run.effective_config, config); });
test("rejects a publish when a dependency changes after validation", async () => { const { service, catalog } = harness(); const draft = await service.create(builder, config, "2026-07-11T00:00:00Z"); const report = await service.preview(builder, draft.id, "2026-07-11T00:01:00Z"); catalog.drift = true; await assert.rejects(() => service.publish(builder, draft.id, report.id, { audience: "private", audience_ids: [builder.id] }, "", "2026-07-11T00:02:00Z"), /dependency_changed/); });
test("denies unauthorized publication, cross-tenant access, and missing org approval", async () => { const { service } = harness(true); const draft = await service.create(builder, config, "2026-07-11T00:00:00Z"); const report = await service.preview(builder, draft.id, "2026-07-11T00:01:00Z"); await assert.rejects(() => service.publish(member, draft.id, report.id, { audience: "organization_directory", audience_ids: [] }, "", "2026-07-11T00:02:00Z"), /permission_denied/); await assert.rejects(() => service.preview(outsider, draft.id, "2026-07-11T00:02:00Z"), /cross-organization/); await assert.rejects(() => service.publish(builder, draft.id, report.id, { audience: "organization_directory", audience_ids: [] }, "", "2026-07-11T00:02:00Z"), /approval_required/); });
test("detects stored version hash tampering before invocation", async () => { const { service, store } = harness(); const draft = await service.create(builder, config, "2026-07-11T00:00:00Z", "agent.ops"); const report = await service.preview(builder, draft.id, "2026-07-11T00:01:00Z"); const { version, deployment } = await service.publish(builder, draft.id, report.id, { audience: "team", audience_ids: ["team.ops"] }, "", "2026-07-11T00:02:00Z"); store.versions.set(version.id, { ...version, config: { ...version.config, instructions: "tampered" } }); await assert.rejects(() => service.resolveForRun(deployment.id, builder, "2026-07-11T00:03:00Z"), /version_integrity_failure/); });
test("updates, rolls back, deprecates inactive releases, and projects favorites and usage", async () => { const { service } = harness(); const draft1 = await service.create(builder, config, "2026-07-11T00:00:00Z", "agent.ops"); const report1 = await service.preview(builder, draft1.id, "2026-07-11T00:01:00Z"); const first = await service.publish(builder, draft1.id, report1.id, { audience: "team", audience_ids: ["team.ops"] }, "v1", "2026-07-11T00:02:00Z"); const draft2 = await service.updateDraft(builder, draft1.id, 1, { ...config, instructions: "Create bounded internal drafts with cited exceptions." }, "2026-07-11T00:03:00Z"); const report2 = await service.preview(builder, draft2.id, "2026-07-11T00:04:00Z"); const second = await service.publish(builder, draft2.id, report2.id, { audience: "team", audience_ids: ["team.ops"] }, "v2", "2026-07-11T00:05:00Z"); assert.equal(second.deployment.revision, 2); const rolledBack = await service.rollback(builder, second.deployment.id, first.version.id, 2, "2026-07-11T00:06:00Z"); assert.equal(rolledBack.active_version_id, first.version.id); await service.deprecate(builder, second.version.id, "2026-07-11T00:07:00Z"); await service.resolveForRun(rolledBack.id, builder, "2026-07-11T00:08:00Z"); await service.favorite(builder, "agent.ops", true); const [entry] = await service.directory(builder, "operations"); assert.equal(entry?.favorite, true); assert.equal(entry?.runs, 1); assert.equal(entry?.version.id, first.version.id); });
test("digest is stable across object key order", async () => { assert.equal(await digest({ b: 2, a: 1 }), await digest({ a: 1, b: 2 })); });
