export type ModelCatalogEntry = {
  id: string;
  openRouterId: string;
  name: string;
  provider: "OpenRouter";
  lab: string;
  tier: string;
  tags: string[];
  description: string;
  personality: string;
  color: string;
  initial: string;
  defaultEnabled: boolean;
  active: boolean;
};

export const curatedCatalog: ModelCatalogEntry[] = [
  {
    id: "gpt-5.4",
    openRouterId: "openai/gpt-5.4",
    name: "GPT-5.4",
    provider: "OpenRouter",
    lab: "OpenAI",
    tier: "flagship",
    tags: ["reasoning", "general", "frontier"],
    description: "OpenAI current top-end GPT-5.4-tier frontier model on OpenRouter.",
    personality: "The tactician. Methodical, broad, and usually difficult to rattle.",
    color: "#879cb3",
    initial: "G2",
    defaultEnabled: true,
    active: true,
  },
  {
    id: "gpt-5.4-mini",
    openRouterId: "openai/gpt-5.4-mini",
    name: "GPT-5.4 Mini",
    provider: "OpenRouter",
    lab: "OpenAI",
    tier: "mini",
    tags: ["fast", "general", "budget"],
    description: "Current lightweight GPT-5.4 variant for faster, cheaper iteration.",
    personality: "The overachiever. Small frame, very little hesitation.",
    color: "#7b93a8",
    initial: "Gm",
    defaultEnabled: false,
    active: true,
  },
  {
    id: "claude-opus-4.6",
    openRouterId: "anthropic/claude-opus-4.6",
    name: "Claude Opus 4.6",
    provider: "OpenRouter",
    lab: "Anthropic",
    tier: "flagship",
    tags: ["reasoning", "writing", "analysis"],
    description: "Anthropic strongest current flagship model for complex, long-horizon work.",
    personality: "The closer. Expensive, deliberate, and built for hard problems.",
    color: "#8f82b8",
    initial: "Co",
    defaultEnabled: true,
    active: true,
  },
  {
    id: "claude-sonnet-4.6",
    openRouterId: "anthropic/claude-sonnet-4.6",
    name: "Claude Sonnet 4.6",
    provider: "OpenRouter",
    lab: "Anthropic",
    tier: "flagship",
    tags: ["reasoning", "writing", "analysis"],
    description: "Anthropic newest Sonnet-class model with stronger coding and agentic performance.",
    personality: "The editor. Refined, careful, and annoyingly articulate.",
    color: "#a190b8",
    initial: "Cs",
    defaultEnabled: false,
    active: true,
  },
  {
    id: "claude-haiku-4.5",
    openRouterId: "anthropic/claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    provider: "OpenRouter",
    lab: "Anthropic",
    tier: "fast",
    tags: ["fast", "writing", "analysis"],
    description: "Anthropic latest Haiku-class model, optimized for fast, lower-cost inference.",
    personality: "The poet. Fast on its feet and rarely boring.",
    color: "#9b8eb8",
    initial: "Ch",
    defaultEnabled: false,
    active: true,
  },
  {
    id: "gemini-3.1-pro-preview",
    openRouterId: "google/gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "OpenRouter",
    lab: "Google DeepMind",
    tier: "flagship",
    tags: ["reasoning", "multimodal", "analysis"],
    description: "Google latest verifiable frontier Pro model on OpenRouter, with 3.1-series upgrades.",
    personality: "The systems thinker. Sees structure everywhere.",
    color: "#7ba894",
    initial: "Gp",
    defaultEnabled: true,
    active: true,
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    openRouterId: "google/gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    provider: "OpenRouter",
    lab: "Google DeepMind",
    tier: "fast",
    tags: ["fast", "multimodal", "budget"],
    description: "Latest verifiable low-latency Gemini 3.1 text-capable Flash-family entry on OpenRouter.",
    personality: "The polymath. Rapid associations, low drag.",
    color: "#75b59c",
    initial: "Gf",
    defaultEnabled: false,
    active: true,
  },
  {
    id: "grok-4.20-beta",
    openRouterId: "x-ai/grok-4.20-beta",
    name: "Grok 4.20 Beta",
    provider: "OpenRouter",
    lab: "xAI",
    tier: "flagship",
    tags: ["reasoning", "frontier", "creative"],
    description: "Latest verifiable single-agent Grok flagship on OpenRouter.",
    personality: "The wildcard. Loves bold swings.",
    color: "#b8896b",
    initial: "G4",
    defaultEnabled: true,
    active: true,
  },
  {
    id: "grok-4.1-fast",
    openRouterId: "x-ai/grok-4.1-fast",
    name: "Grok 4.1 Fast",
    provider: "OpenRouter",
    lab: "xAI",
    tier: "fast",
    tags: ["fast", "creative", "analysis"],
    description: "Fast Grok 4-family variant for lower-latency runs.",
    personality: "The sprinter. Often first, often loud.",
    color: "#b8896b",
    initial: "Gk",
    defaultEnabled: false,
    active: true,
  },
  {
    id: "deepseek-v3.2",
    openRouterId: "deepseek/deepseek-v3.2",
    name: "DeepSeek V3.2",
    provider: "OpenRouter",
    lab: "DeepSeek",
    tier: "reasoning",
    tags: ["reasoning", "open-weight", "frontier"],
    description: "DeepSeek reasoning-specialized frontier model and the strongest verified DeepSeek catalog entry here.",
    personality: "The challenger. Efficient and surprisingly sharp.",
    color: "#4da1a9",
    initial: "Dr",
    defaultEnabled: false,
    active: true,
  },
  {
    id: "kimi-k2.5",
    openRouterId: "moonshotai/kimi-k2.5",
    name: "Kimi K2.5",
    provider: "OpenRouter",
    lab: "Moonshot AI",
    tier: "flagship",
    tags: ["reasoning", "long-context", "frontier"],
    description: "Moonshot latest Kimi K2.5 release on OpenRouter.",
    personality: "The archivist. Likes large context and neat synthesis.",
    color: "#6d8fcb",
    initial: "K2",
    defaultEnabled: false,
    active: true,
  },
  {
    id: "glm-5.1",
    openRouterId: "z-ai/glm-5.1",
    name: "GLM 5.1",
    provider: "OpenRouter",
    lab: "Zhipu AI",
    tier: "flagship",
    tags: ["general", "analysis", "frontier"],
    description: "Latest verified flagship GLM-family model on OpenRouter.",
    personality: "The operator. Balanced, steady, unfussy.",
    color: "#7b6bc7",
    initial: "Gl",
    defaultEnabled: false,
    active: true,
  },
  {
    id: "glm-5-turbo",
    openRouterId: "z-ai/glm-5-turbo",
    name: "GLM 5 Turbo",
    provider: "OpenRouter",
    lab: "Zhipu AI",
    tier: "fast",
    tags: ["fast", "analysis", "agentic"],
    description: "Fast GLM 5-series option optimized for coding and tool-heavy agent work.",
    personality: "The operator deputy. Leaner, quicker, still composed.",
    color: "#8877d6",
    initial: "Gf",
    defaultEnabled: false,
    active: true,
  },
];

export const activeModelCatalog = curatedCatalog.filter((entry) => entry.active);

export const defaultCompareModels = activeModelCatalog
  .filter((entry) => entry.defaultEnabled)
  .map((entry) => entry.openRouterId)
  .slice(0, 4);

export const defaultChatModel = activeModelCatalog[0]?.openRouterId ?? "openai/gpt-5.4";
