import { useState, type FormEvent } from "react";
import type { CollaborationActions, CommentView, ReviewView } from "../../features/collaboration/model";
import "../outputs/output-workbench.css";

interface CollaborationRailProps { readonly comments: readonly CommentView[]; readonly reviews: readonly ReviewView[]; readonly actions: CollaborationActions; readonly canComment: boolean; }
export function CollaborationRail({ comments, reviews, actions, canComment }: CollaborationRailProps) {
  const [body, setBody] = useState(""); const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const value = body.trim(); if (!value || !canComment) return; void Promise.resolve(actions.onAddComment(value)).then(() => setBody("")); };
  return <aside className="collaboration-rail" aria-labelledby="comments-heading"><div className="output-section-heading"><h2 id="comments-heading">Review</h2><button type="button" onClick={() => void actions.onRequestReview()}>Request review</button></div>{reviews.length ? <ul className="review-list">{reviews.map((review) => <li key={review.id} data-status={review.status}><strong>{review.reviewer}</strong><span>{review.status.replace("_", " ")}</span>{review.note ? <p>{review.note}</p> : null}{review.status === "pending" && review.canDecide && actions.onDecideReview ? <div className="output-review-actions"><button type="button" onClick={() => void actions.onDecideReview?.(review.id, "approved")}>Approve</button><button type="button" onClick={() => void actions.onDecideReview?.(review.id, "changes_requested")}>Request changes</button></div> : null}</li>)}</ul> : <p>No reviewers assigned.</p>}<h3>Comments</h3>{comments.length ? <ol className="comment-list">{comments.map((comment) => <li key={comment.id}><div><strong>{comment.author}</strong><time dateTime={comment.createdAt}>{new Date(comment.createdAt).toLocaleString()}</time></div><small>{comment.anchorLabel}</small><p>{comment.body}</p>{!comment.resolved ? <button type="button" onClick={() => void actions.onResolve(comment.id)}>Resolve</button> : <span>Resolved</span>}</li>)}</ol> : <p>No comments yet. Select content to anchor the first note.</p>}<form onSubmit={submit}><label htmlFor="collaboration-comment">Add a comment</label><textarea id="collaboration-comment" value={body} onChange={(event) => setBody(event.target.value)} disabled={!canComment} placeholder={canComment ? "Write a specific review note" : "Comment permission is required"} /><button type="submit" disabled={!canComment || !body.trim()}>Comment</button></form></aside>;
}
